export default [
	{
		adult: false,
		backdrop_path: '/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg',
		id: 569094,
		title: 'Spider-Man: Across the Spider-Verse',
		original_language: 'en',
		original_title: 'Spider-Man: Across the Spider-Verse',
		overview:
			'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
		poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
		media_type: 'movie',
		genre_ids: [28, 12, 16, 878],
		popularity: 1963.23,
		release_date: '2023-05-31',
		video: false,
		vote_average: 8.756,
		vote_count: 389
	},
	{
		adult: false,
		backdrop_path: '/aEHwpKJyLB56AqR7SPBje5L8M79.jpg',
		id: 961718,
		title: 'Medellin',
		original_language: 'fr',
		original_title: 'Medellin',
		overview:
			"To save his little brother from the hands of dangerous narcos of the Medellín cartel, Reda has a plan that is as simple as it is totally insane: put together a team and raid Colombia. But this adventure is going to get completely out of control when he decides to kidnap the son of the cartel leader to exchange him for his brother's life.",
		poster_path: '/jKFOQ5LNQuIWGLdB2WhVlSUcS6F.jpg',
		media_type: 'movie',
		genre_ids: [28, 35],
		popularity: 70.976,
		release_date: '2023-06-01',
		video: false,
		vote_average: 5.12,
		vote_count: 25
	},
	{
		adult: false,
		backdrop_path: '/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg',
		id: 603692,
		title: 'John Wick: Chapter 4',
		original_language: 'en',
		original_title: 'John Wick: Chapter 4',
		overview:
			'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
		poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
		media_type: 'movie',
		genre_ids: [28, 53, 80],
		popularity: 6036.288,
		release_date: '2023-03-22',
		video: false,
		vote_average: 7.956,
		vote_count: 2582
	},
	{
		adult: false,
		backdrop_path: '/1IM8i8HiomFC4y6NRyBuDrHJWg3.jpg',
		id: 447277,
		title: 'The Little Mermaid',
		original_language: 'en',
		original_title: 'The Little Mermaid',
		overview:
			'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
		poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
		media_type: 'movie',
		genre_ids: [12, 10751, 14, 10749],
		popularity: 2077.247,
		release_date: '2023-05-18',
		video: false,
		vote_average: 6.087,
		vote_count: 447
	},
	{
		adult: false,
		backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
		id: 502356,
		title: 'The Super Mario Bros. Movie',
		original_language: 'en',
		original_title: 'The Super Mario Bros. Movie',
		overview:
			'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
		poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
		media_type: 'movie',
		genre_ids: [16, 10751, 12, 14, 35],
		popularity: 4551.163,
		release_date: '2023-04-05',
		video: false,
		vote_average: 7.769,
		vote_count: 4096
	},
	{
		adult: false,
		backdrop_path: '/cUHxmWfkp6se0Rt10Kr86bMCYDE.jpg',
		id: 1016084,
		title: 'BlackBerry',
		original_language: 'en',
		original_title: 'BlackBerry',
		overview:
			"Two mismatched entrepreneurs – egghead innovator Mike Lazaridis and cut-throat businessman Jim Balsillie – joined forces in an endeavour that was to become a worldwide hit in little more than a decade. The story of the meteoric rise and catastrophic demise of the world's first smartphone.",
		poster_path: '/neV35lK7em4rIY9QIoH1cruErPA.jpg',
		media_type: 'movie',
		genre_ids: [35, 18, 36],
		popularity: 31.389,
		release_date: '2023-05-11',
		video: false,
		vote_average: 7.826,
		vote_count: 23
	},
	{
		adult: false,
		backdrop_path: '/vQ5T84t8h4N2xAswNFW9fkVIyZq.jpg',
		id: 536437,
		title: 'Hypnotic',
		original_language: 'en',
		original_title: 'Hypnotic',
		overview:
			'A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.',
		poster_path: '/3IhGkkalwXguTlceGSl8XUJZOVI.jpg',
		media_type: 'movie',
		genre_ids: [80, 9648, 53],
		popularity: 178.374,
		release_date: '2023-05-11',
		video: false,
		vote_average: 6.657,
		vote_count: 99
	},
	{
		adult: false,
		backdrop_path: '/4t0oBFrJyweYPt0hocW6RUa0b6H.jpg',
		id: 385687,
		title: 'Fast X',
		original_language: 'en',
		original_title: 'Fast X',
		overview:
			"Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
		poster_path: '/1E5baAaEse26fej7uHcjOgEE2t2.jpg',
		media_type: 'movie',
		genre_ids: [28, 80, 53],
		popularity: 2996.613,
		release_date: '2023-05-17',
		video: false,
		vote_average: 7.017,
		vote_count: 777
	},
	{
		adult: false,
		backdrop_path: '/oblUNeHlwV3VsjB5ITMlco5ZSOF.jpg',
		id: 493529,
		title: 'Dungeons & Dragons: Honor Among Thieves',
		original_language: 'en',
		original_title: 'Dungeons & Dragons: Honor Among Thieves',
		overview:
			'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
		poster_path: '/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg',
		media_type: 'movie',
		genre_ids: [12, 14, 35],
		popularity: 572.286,
		release_date: '2023-03-23',
		video: false,
		vote_average: 7.47,
		vote_count: 1579
	},
	{
		adult: false,
		backdrop_path: '/jwobZgmrUPPBLA6Jvuxpm8JOGvZ.jpg',
		id: 1119173,
		title: 'A Beautiful Life',
		original_language: 'da',
		original_title: 'A Beautiful Life',
		overview:
			"When a young fisherman with a hidden talent gets discovered by a music producer, he must decide if he's ready to open himself up to stardom — and love.",
		poster_path: '/5Atl4F2inzhrq8LCu7xl7OajLQ3.jpg',
		media_type: 'movie',
		genre_ids: [18, 10402, 10749],
		popularity: 79.722,
		release_date: '2023-06-01',
		video: false,
		vote_average: 7.155,
		vote_count: 29
	},
	{
		adult: false,
		backdrop_path: '/jqwM0nhOLEFI1HHBabwr80Od3TC.jpg',
		id: 324857,
		title: 'Spider-Man: Into the Spider-Verse',
		original_language: 'en',
		original_title: 'Spider-Man: Into the Spider-Verse',
		overview:
			'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
		poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
		media_type: 'movie',
		genre_ids: [28, 12, 16, 878],
		popularity: 796.719,
		release_date: '2018-12-06',
		video: false,
		vote_average: 8.404,
		vote_count: 12895
	},
	{
		adult: false,
		backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
		id: 640146,
		title: 'Ant-Man and the Wasp: Quantumania',
		original_language: 'en',
		original_title: 'Ant-Man and the Wasp: Quantumania',
		overview:
			"Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
		poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
		media_type: 'movie',
		genre_ids: [28, 12, 878],
		popularity: 1578.299,
		release_date: '2023-02-15',
		video: false,
		vote_average: 6.497,
		vote_count: 3116
	},
	{
		adult: false,
		backdrop_path: '/oajM1sjjkXBkU9CgyAmeABmalZk.jpg',
		id: 1126852,
		title: 'Rich in Love 2',
		original_language: 'pt',
		original_title: 'Ricos de Amor 2',
		overview:
			"When the idealistic Paula resumes her work as a volunteer doctor in the Amazon, Teto convinces his partners to establish their tomato cooperative in a village in the region. But to win back Paula's heart and save the company from bankruptcy, Teto must definitely overcome his spoiled playboy habits and face the interests of a powerful farmer, who stands in his way.",
		poster_path: '/gA2emLQTNb8XS1646Nmhp91NNgv.jpg',
		media_type: 'movie',
		genre_ids: [10749, 35],
		popularity: 59.144,
		release_date: '2023-06-02',
		video: false,
		vote_average: 6.75,
		vote_count: 6
	},
	{
		adult: false,
		backdrop_path: '/rH3jY9JN9krUyE0Q3WLNtujMs8.jpg',
		id: 667538,
		title: 'Transformers: Rise of the Beasts',
		original_language: 'en',
		original_title: 'Transformers: Rise of the Beasts',
		overview:
			"A '90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
		poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
		media_type: 'movie',
		genre_ids: [28, 12, 878],
		popularity: 452.891,
		release_date: '2023-06-06',
		video: false,
		vote_average: 9.7,
		vote_count: 7
	},
	{
		adult: false,
		backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
		id: 447365,
		title: 'Guardians of the Galaxy Vol. 3',
		original_language: 'en',
		original_title: 'Guardians of the Galaxy Vol. 3',
		overview:
			'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
		poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
		media_type: 'movie',
		genre_ids: [878, 12, 28],
		popularity: 1345.038,
		release_date: '2023-05-03',
		video: false,
		vote_average: 8.134,
		vote_count: 1801
	},
	{
		adult: false,
		backdrop_path: '/mK0a3t62lM8ho3mmvBWf6NxdWvw.jpg',
		id: 532408,
		title: 'The Boogeyman',
		original_language: 'en',
		original_title: 'The Boogeyman',
		overview:
			'Still reeling from the tragic death of their mother, a teenage girl and her younger sister find themselves plagued by a sadistic presence in their house and struggle to get their grieving father to pay attention before it’s too late.',
		poster_path: '/156VTRLwgoUQZnmGmqtuhKuK8vy.jpg',
		media_type: 'movie',
		genre_ids: [27, 9648],
		popularity: 166.287,
		release_date: '2023-05-31',
		video: false,
		vote_average: 6.242,
		vote_count: 33
	},
	{
		adult: false,
		backdrop_path: '/eTvN54pd83TrSEOz6wbsXEJktCV.jpg',
		id: 882569,
		title: "Guy Ritchie's The Covenant",
		original_language: 'en',
		original_title: "Guy Ritchie's The Covenant",
		overview:
			'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
		poster_path: '/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg',
		media_type: 'movie',
		genre_ids: [10752, 28, 53],
		popularity: 1267.774,
		release_date: '2023-04-19',
		video: false,
		vote_average: 7.556,
		vote_count: 439
	},
	{
		adult: false,
		backdrop_path: '/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
		id: 890771,
		title: 'The Black Demon',
		original_language: 'en',
		original_title: 'The Black Demon',
		overview:
			"Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
		poster_path: '/uiFcFIjig0YwyNmhoxkxtAAVIL2.jpg',
		media_type: 'movie',
		genre_ids: [27, 53],
		popularity: 520.617,
		release_date: '2023-04-26',
		video: false,
		vote_average: 6.338,
		vote_count: 74
	},
	{
		adult: false,
		backdrop_path: '/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg',
		id: 700391,
		title: '65',
		original_language: 'en',
		original_title: '65',
		overview:
			'65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
		poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
		media_type: 'movie',
		genre_ids: [878, 12, 53],
		popularity: 260.344,
		release_date: '2023-03-02',
		video: false,
		vote_average: 6.235,
		vote_count: 1162
	},
	{
		adult: false,
		backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
		id: 76600,
		title: 'Avatar: The Way of Water',
		original_language: 'en',
		original_title: 'Avatar: The Way of Water',
		overview:
			'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
		poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
		media_type: 'movie',
		genre_ids: [878, 12, 28],
		popularity: 1214.834,
		release_date: '2022-12-14',
		video: false,
		vote_average: 7.7,
		vote_count: 8306
	}
];
